theme: jekyll-theme-minimal
title: Jay's Webpage
description: >
  Pronouns in use: they/them/theirs.
  Learn a bit about me and check out my data science projects!
  [LinkedIn](https://www.linkedin.com/in/jay-francis46/)
  [Email](mailto:jay.e.francis46@gmail.com)
